### ISSUE TITLE
quarks native adapt

### ISSUE THREAD

**Issue by kkk25641463** [Captain-P-Goldfish/SCIM-SDK#317]
Is there any plant or roadmap to adapt quarks native mode?

**Comment by Captain-P-Goldfish** [comment]
There is no need to do so. GraalVM does already offer everything needed here.
I saw the ticket that you directly closed again. This was based to the missing resources of the `scim-sdk-common` module. This can be fixed by adding a property within your application.properties file `quarkus.native.resources.includes=de/captaingoldfish/scim/sdk/**` 

Additionally GraalVM will remove all methods and constructors not directly used by the sourceCode so in order for you to make it work you have create a huge list of entries within your `reflection.config.json` file in order to prevent GraalVM from doing so. I added a quarkus example project that started this list but I currently have no obligation to finish it. But I would if you want to do so I would gladly accept a pull request.

For more details on this issue see: https://quarkus.io/guides/writing-native-applications-tips

**Comment by kkk25641463** [comment]
Thanks a lot.I will check and complete example code.

**Comment by kkk25641463** [comment]
I test Quarkus in jvm model. JsonHelper.loadJsonDocument did not work.
But below code is ok.

```
public static JsonNode loadJsonDocument(String classPathLocation)
  {
    try (InputStream inputStream = Thread.currentThread().getContextClassLoader().getResourceAsStream(classPathLocation))
    {
      return new ObjectMapper().readTree(inputStream);
    }
    catch (IOException e)
    {
      throw new de.captaingoldfish.scim.sdk.common.exceptions.IOException(e.getMessage(), e, null, null);
    }
  }

  public UserEndpoint(Bus bus)
  {
    super(loadJsonDocument(USER_RESOURCE_TYPE_LOCATION),
            loadJsonDocument(USER_SCHEMA_LOCATION), null, new UserHandler(bus));
  }

```

**Comment by Captain-P-Goldfish** [comment]
Are you still testing within native application? Did you remember to add the required resource files by using the property `quarkus.native.resources.includes` within the application.properties file?

**Comment by kkk25641463** [comment]
Yes, I test both native and jvm mode.Here is the config:
```
quarkus:
  transaction-manager:
    default-transaction-timeout: 300
  native:
    additional-build-args:
      -H:ReflectionConfigurationFiles=reflection-config.json
    resources:
      includes: com/pesco/base/interfaces/scim2/sdk/**,de/captaingoldfish/scim/sdk/**
```
<img width="382" alt="image" src="https://user-images.githubusercontent.com/1751500/186420338-bd61d1e3-acae-4dc5-b77b-ee8b35ba6430.png">
